services:
  code-profiler-openenv:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ../../src:/app/src
      - ../../profiles:/app/profiles
      - ../../logs:/app/logs
    networks:
      - profiler-network

  python-container:
    build:
      context: ./server/python
      dockerfile: Dockerfile
    environment:
      - AUSTIN_ENABLED=true
    ports:
      - "8100:8080"
    volumes:
      - ./server/python/src:/app/src
      - ../../profiles:/app/profiles
    networks:
      - profiler-network

  java-container:
    build:
      context: ./server/java
      dockerfile: Dockerfile
    environment:
      - ASYNC_PROFILER_ENABLED=true
    ports:
      - "8200:8080"
    volumes:
      - ./server/java/src:/app/src
      - ../../profiles:/app/profiles
    networks:
      - profiler-network

  cpp-container:
    build:
      context: ./server/cpp
      dockerfile: Dockerfile
    environment:
      - AUSTIN_ENABLED=true
    ports:
      - "8300:8080"
    volumes:
      - ./server/cpp/src:/app/src
      - ../../profiles:/app/profiles
    networks:
      - profiler-network

networks:
  profiler-network:
    driver: bridge
